name: Preview Deployment

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'preview-${{ github.event.pull_request.number }}'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build with Next.js
        run: yarn build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages Preview
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: 'preview-${{ github.event.pull_request.number }}'
          token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      preview_url: ${{ steps.deployment.outputs.page_url }}

  comment:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `Preview URL: ${{ needs.build-and-deploy.outputs.preview_url }}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: previewUrl
            });
